ElectronicClassbook/Web/Areas/Admin/Models/SubjectViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Models.Submodels;

namespace Web.Areas.Admin.Models
{
	public class SubjectViewModel
	{
		public int Id { get; set; }
		[Display(Name="Zkratka")]
		[Required(ErrorMessage = "Povinná položka")]
		public string Code { get; set; }
		[Display(Name = "Název")]
		[Required(ErrorMessage = "Povinná položka")]
		public string Name { get; set; }
		public TeacherSubModel Teachers { get; set; } = new TeacherSubModel();
	}
}

ElectronicClassbook/Web/Areas/Admin/Controllers/SubjectController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Admin.Interfaces;
using Common;
using DataAccess.EntityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using Web.Areas.Admin.Models;

namespace Web.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin")]
	[Area("Admin")]
	[Route("subject")]
	public class SubjectController : Controller
	{
		private readonly IAdminManager adminManager;
		public SubjectController(IAdminManager adminManager)
		{
			this.adminManager = adminManager;
		}
		public IActionResult Index(int pageNumber = 1)
		{
			List<SubjectViewModel> model = new List<SubjectViewModel>();

			var subjects = adminManager.GetAllSubjects();
			foreach (var s in subjects)
			{
				model.Add(new SubjectViewModel()
				{
					Id = s.Id,
					Code = s.Code,
					Name = s.Name,

				});
			}

			return View(PaginatedList<SubjectViewModel>.Create(model.AsQueryable(), pageNumber, 5));
		}

		[HttpGet]
		[Route("AddSubject")]
		public IActionResult AddSubject()
		{

			SubjectViewModel model = new SubjectViewModel();

			this.FillTeachers(ref model);

			return View(model);
		}

		[HttpPost]
		[Route("AddSubject")]
		public IActionResult AddSubject(SubjectViewModel model)
		{

			Subject s = new Subject();
			s.Code = model.Code;
			s.Name = model.Name;
			s.TeacherSubjects = new List<TeacherSubject>();

			if (model.Teachers.TeacherIds != null && model.Teachers.TeacherIds.Length > 0)
			{
				List<Teacher> teachers = adminManager.GetTeachersById(model.Teachers.TeacherIds);
				foreach (var t in teachers)
				{
					s.TeacherSubjects.Add(new TeacherSubject()
					{
						Subject = s,
						Teacher = t
					});
				}
			}

			if (!adminManager.CreateSubject(s))
			{
				this.FillTeachers(ref model);
				ModelState.AddModelError("", "Někde se stala chyba. Předmět nebyl vytvořen.");
				return View(model);
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Route("EditSubject")]
		public IActionResult EditSubject(int id)
		{
			Subject s = adminManager.GetSubjectById(id);
			SubjectViewModel model = new SubjectViewModel();
			this.FillTeachers(ref model);

			model.Id = s.Id;
			model.Code = s.Code;
			model.Name = s.Name;

			//get student's parents
			int[] teachersIds = new int[s.TeacherSubjects.Select(t => t.Teacher).Count()];
			for (int i = 0; i < s.TeacherSubjects.Select(t => t.Teacher).Count(); i++)
			{
				teachersIds[i] = s.TeacherSubjects.Select(t => t.Teacher).ElementAt(i).Id;
			}
			model.Teachers.TeacherIds = teachersIds;


			return View(model);
		}

		[HttpPost]
		[Route("EditSubject")]
		public IActionResult EditSubject(SubjectViewModel model)
		{
			Subject s = adminManager.GetSubjectById(model.Id);
			s.Code = model.Code;
			s.Name = model.Name;

			if (model.Teachers.TeacherIds != null && model.Teachers.TeacherIds.Length > 0)
			{
				//handle students
				List<Teacher> teachers = adminManager.GetTeachersById(model.Teachers.TeacherIds);

				//remove
				var teacherSubjects = s.TeacherSubjects.ToList();
				foreach (var ts in teacherSubjects)
				{
					if (teachers == null || !teachers.Contains(ts.Teacher))
					{
						s.TeacherSubjects.Remove(ts);
					}
				}
				if (teachers != null)
				{
					//add
					foreach (var t in teachers)
					{
						if (!s.TeacherSubjects.Select(x => x.Teacher).Contains(t))
						{
							s.TeacherSubjects.Add(new TeacherSubject()
							{
								Teacher = t,
								Subject = s
							});
						}
					}
				}
			}
			else if(s.TeacherSubjects.Count > 0)
			{
				s.TeacherSubjects = new List<TeacherSubject>();
			}

			if (!adminManager.UpdateSubject(s))
			{
				this.FillTeachers(ref model);
				ModelState.AddModelError("", "Někde se stala chyba. Změny nebyly provedeny.");
				return View(model);
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Route("DetailSubject")]
		public IActionResult DetailSubject(int id)
		{
			Subject s = adminManager.GetSubjectById(id);
			SubjectDetailViewModel model = new SubjectDetailViewModel();
			if (s != null)
			{
				model.Code = s.Code;
				model.Name = s.Name;
				model.Teachers = s.TeacherSubjects.Select(x => x.Teacher).ToList();
			}
			return View(model);
		}

		[HttpGet]
		[Route("DeleteSubject")]
		public IActionResult DeleteSubject(int id)
		{
			Subject s = adminManager.GetSubjectById(id);
			if (s != null)
			{
				adminManager.DeleteSubject(s);
			}
			return RedirectToAction("Index");
		}

		private void FillTeachers(ref SubjectViewModel model)
		{
			var teachers = adminManager.GetAllTeachers();

			foreach (var t in teachers)
			{
				model.Teachers.Teachers.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = t.LastName + " " + t.FirstName + " (" + t.Email + ")",
					Value = t.Id.ToString()
				});
			}
		}
	}
}

ElectronicClassbook/Web/Areas/Admin/Views/Subject/AddSubject.cshtml
@model Web.Areas.Admin.Models.SubjectViewModel

@{
    ViewData["Title"] = "Přidat předmět";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Přidat nový předmět</h5>
            </div>

            <div class="card-body">
                <form asp-action="AddSubject">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Code" class="control-label"></label>
                        <input asp-for="Code" class="form-control" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Teachers.TeacherIds, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Teachers.TeacherIds, new MultiSelectList(Model.Teachers?.Teachers, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "SubjectsDropdown" })
                        </div>
                    </div>

                    <div>
                        <div class="form-group d-inline float-right">
                            <input type="submit" value="Vytvořit předmět" class="btn btn-primary" />
                        </div>
                        <div class="d-inline">
                            <a asp-action="Index">Zpět</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ElectronicClassbook/Web/Areas/Admin/Views/Subject/DetailSubject.cshtml
@model Web.Areas.Admin.Models.SubjectDetailViewModel

@{
    ViewData["Title"] = "Detail předmětu";
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Detail předmětu</h5>
            </div>

            <div class="card-body">
                <div class="form-group col-md">
                    <label asp-for="Code" class="control-label"></label>
                    <label class="form-control">@Model.Code</label>
                </div>
                <div class="form-group col-md">
                    <label asp-for="Name" class="control-label"></label>
                    <label class="form-control">@Model.Name</label>
                </div>


                <div class="form-group row">
                    @Html.LabelFor(model => model.Teachers, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-6">
                        <ul>
                            @if (Model.Teachers.Count > 0)
                            {
                                @foreach (var teacher in Model.Teachers)
                                {
                                    <li>@teacher.LastName @teacher.FirstName (@teacher.Email)</li>
                                }
                            }
                        </ul>
                    </div>
                </div>

                <div>
                    <a asp-action="Index">Zpět</a>
                </div>

            </div>

        </div>
    </div>
</div>

ElectronicClassbook/Web/Areas/Admin/Views/Subject/EditSubject.cshtml
@model Web.Areas.Admin.Models.SubjectViewModel

@{
    ViewData["Title"] = "Editovat předmět";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Editovat předmět</h5>
            </div>

            <div class="card-body">
                <form asp-action="EditSubject">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        <label asp-for="Code" class="control-label"></label>
                        <input asp-for="Code" class="form-control" />
                        <span asp-validation-for="Code" class="text-danger"></span>
                    </div>

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>



                    <div class="form-group row">
                        @Html.LabelFor(model => model.Teachers.TeacherIds, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Teachers.TeacherIds, new MultiSelectList(Model.Teachers.Teachers, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "StudentsDropdown" })
                        </div>
                    </div>

                    <div>
                        <div class="form-group d-inline float-right">
                            <input type="submit" value="Potvrdit změnu" class="btn btn-primary" />
                        </div>
                        <div class="d-inline">
                            <a asp-action="Index">Zpět</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

ElectronicClassbook/Web/Areas/Admin/Views/Subject/Index.cshtml
@model PaginatedList<Web.Areas.Admin.Models.SubjectViewModel>
@{
    ViewData["Title"] = "Předměty";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5 class="d-inline">Předměty</h5>

                @* Tlačítko na přidání předmětu *@
                <div class="float-right d-inline">
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Subject" asp-action="AddSubject">Přidat předmět</a>
                </div>
            </div>

            <div class="card-body">
                @if (Model.Count > 0)
                {
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col"> Zkratka</th>
                                    <th scope="col"> Název</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Code)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            <div class="container">
                                                <div class="btn-group blocks" role="button">
                                                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Subject" asp-action="DetailSubject" asp-route-id="@item.Id">Detail</a>
                                                    <a class="btn btn-success" asp-area="Admin" asp-controller="Subject" asp-action="EditSubject" asp-route-id="@item.Id">Edit</a>
                                                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Subject" asp-action="DeleteSubject" asp-route-id="@item.Id">Smazat</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.HasNextPage ? "disabled" : "";

                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="btn btn-default @prevDisabled">
                        Předchozí
                    </a>
                    <a asp-action="Index"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]"
                       class="btn btn-default @nextDisabled">
                        Další
                    </a>
                }
                else
                {
                    <div>Žádné předměty k zobrazení.</div>
                }
            </div>
        </div>
    </div>
</div>





@* Seznam předmětů s akcemi Edit a Smazat *@
@*<table class="table table-hover">
        <thead>
            <tr>
                <th scope="col"> Zkratka</th>
                <th scope="col"> Název</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Code)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a class="btn btn-primary" asp-area="Admin" asp-controller="Subject" asp-action="DetailSubject" asp-route-id="@item.Id">Detail</a>
                        <a class="btn btn-success" asp-area="Admin" asp-controller="Subject" asp-action="EditSubject" asp-route-id="@item.Id">Edit</a>
                        <a class="btn btn-danger" asp-area="Admin" asp-controller="Subject" asp-action="DeleteSubject" asp-route-id="@item.Id">Smazat</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

    @{
        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
    }

    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex - 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @prevDisabled">
        Předchozí
    </a>
    <a asp-action="Index"
       asp-route-sortOrder="@ViewData["CurrentSort"]"
       asp-route-pageNumber="@(Model.PageIndex + 1)"
       asp-route-currentFilter="@ViewData["CurrentFilter"]"
       class="btn btn-default @nextDisabled">
        Další
    </a>*@