ElectronicClassbook/Web/Areas/Admin/Models/ClassViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Models.Submodels;

namespace Web.Areas.Admin.Models
{
	public class ClassViewModel
	{
		public int Id { get; set; }
		[Display(Name = "Název")]
		[Required(ErrorMessage = "Povinná položka")]
		public string Name { get; set; }
		public StudentSubModel Students { get; set; } = new StudentSubModel();
		public ClassTeacherSubModel ClassTeacher { get; set; } = new ClassTeacherSubModel();
		public SubjectSubModel Subjects { get; set; } = new SubjectSubModel();
	}
}

ElectronicClassbook/Web/Areas/Admin/Controllers/ClassController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Admin.Interfaces;
using Common;
using DataAccess.EntityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Admin.Models;

namespace Web.Areas.Admin.Controllers
{
	[Authorize(Roles = "Admin")]
	[Area("Admin")]
	[Route("class")]
	public class ClassController : Controller
	{
		private readonly IAdminManager adminManager;
		public ClassController(IAdminManager adminManager)
		{
			this.adminManager = adminManager;
		}
		public IActionResult Index(int pageNumber = 1)
		{
			List<ClassViewModel> model = new List<ClassViewModel>();

			//get all users to UserViewModel
			var classes = adminManager.GetAllClasses().OrderBy(x => x.Name);

			foreach (var c in classes)
			{
				model.Add(new ClassViewModel()
				{
					Id = c.Id,
					Name = c.Name
				});
			}

			return View(PaginatedList<ClassViewModel>.Create(model.AsQueryable(), pageNumber, 5));
		}

		[HttpGet]
		[Route("AddClass")]
		public IActionResult AddClass()
		{
			ClassViewModel model = new ClassViewModel();
			this.FillStudents(ref model);
			this.FillClassTeachers(ref model);
			this.FillSubjects(ref model);

			return View(model);
		}

		[HttpPost]
		[Route("AddClass")]
		public IActionResult AddClass(ClassViewModel model)
		{
			Class c = new Class();
			c.Name = model.Name;
			c.ClassTeacher = adminManager.GetAllClassTeachers().Where(x => x.Id.Equals(model.ClassTeacher.ClassTeacherId)).FirstOrDefault();
			c.Students = adminManager.GetStudentsById(model.Students.StudentsId);

			if (model.Subjects.SubjectsId != null && model.Subjects.SubjectsId.Length > 0)
			{
				//add subjects
				List<Subject> subjects = adminManager.GetSubjectsById(model.Subjects.SubjectsId);
				c.ClassSubjects = new List<ClassSubject>();
				foreach (var s in subjects)
				{
					c.ClassSubjects.Add(new ClassSubject()
					{
						Subject = s,
						Class = c
					});
				}
			}

			if (!adminManager.CreateClass(c))
			{
				this.FillStudents(ref model);
				this.FillClassTeachers(ref model);
				this.FillSubjects(ref model);
				ModelState.AddModelError("", "Někde se stala chyba. Třída nebyla vytvořena.");
				return View(model);
			}


			return RedirectToAction("Index");
		}

		[HttpGet]
		[Route("EditClass")]
		public IActionResult EditClass(int id)
		{
			Class c = adminManager.GetClassById(id);
			ClassViewModel model = new ClassViewModel();
			this.FillClassTeachers(ref model);
			this.FillStudents(ref model);
			this.FillSubjects(ref model);

			model.Id = c.Id;
			model.Name = c.Name;
			if (c.ClassTeacher != null)
				model.ClassTeacher.ClassTeacherId = c.ClassTeacher.Id;

			//get student's parents
			if (c.Students != null)
			{
				int[] studentsIds = new int[c.Students.Count];
				for (int i = 0; i < c.Students.Count; i++)
				{
					studentsIds[i] = c.Students.ElementAt(i).Id;
				}
				model.Students.StudentsId = studentsIds;
			}

			if (c.ClassSubjects != null)
			{
				int[] subjectsIds = new int[c.ClassSubjects.Count];
				for (int i = 0; i < c.ClassSubjects.Count; i++)
				{
					subjectsIds[i] = c.ClassSubjects.ElementAt(i).SubjectId;
				}
				model.Subjects.SubjectsId = subjectsIds;
			}


			return View(model);
		}

		[HttpPost]
		[Route("EditClass")]
		public IActionResult EditClass(ClassViewModel model)
		{

			Class c = adminManager.GetClassById(model.Id);
			c.Name = model.Name;
			c.ClassTeacher = adminManager.GetAllClassTeachers().Where(x => x.Id.Equals(model.ClassTeacher.ClassTeacherId)).FirstOrDefault();

			if (model.Students.StudentsId != null && model.Students.StudentsId.Length > 0)
			{
				//handle students
				List<Student> students = adminManager.GetStudentsById(model.Students.StudentsId);
				if (c.Students != null)
				{
					//remove
					var classStudents = c.Students.ToList();
					foreach (var s in classStudents)
					{
						if (students == null || !students.Contains(s))
						{
							c.Students.Remove(s);
						}
					}
				}
				if (students != null)
				{
					//add
					foreach (var s in students)
					{
						if (!c.Students.Contains(s))
						{
							c.Students.Add(s);
						}
					}
				}
			}
			else if(c.Students.Count > 0)
			{
				c.Students = new List<Student>();
			}

			if (model.Subjects.SubjectsId != null && model.Subjects?.SubjectsId?.Length > 0)
			{
				//handle subjects
				List<Subject> subjects = adminManager.GetSubjectsById(model.Subjects.SubjectsId);
				//remove
				if (c.ClassSubjects != null)
				{
					var classSubjects = c.ClassSubjects.ToList();
					foreach (var s in classSubjects)
					{
						if (!subjects.Contains(s.Subject))
						{
							c.ClassSubjects.Remove(s);
						}
					}
				}
				//add
				if (subjects != null)
				{
					foreach (var s in subjects)
					{
						if (!c.ClassSubjects.Select(x => x.Subject).Contains(s))
						{
							c.ClassSubjects.Add(new ClassSubject()
							{
								Subject = s,
								Class = c
							});
						}
					}
				}
			}
			else if (c.ClassSubjects.Count > 0)
			{
				c.ClassSubjects = new List<ClassSubject>();
			}

			if (!adminManager.UpdateClass(c))
			{
				this.FillClassTeachers(ref model);
				this.FillStudents(ref model);
				this.FillSubjects(ref model);
				ModelState.AddModelError("", "Někde se stala chyba. Úpravy nebyly provedeny.");
				return View(model);
			}

			return RedirectToAction("Index");
		}

		[HttpGet]
		[Route("DetailClass")]
		public IActionResult DetailClass(int id)
		{
			Class c = adminManager.GetClassById(id);
			ClassDetailViewModel model = new ClassDetailViewModel();
			if (c != null)
			{
				model.Name = c.Name;
				model.ClassTeacher = c.ClassTeacher;
				model.Students = c.Students.ToList();
				model.Subjects = c.ClassSubjects.Select(x => x.Subject).ToList();

			}
			return View(model);
		}

		[HttpGet]
		[Route("DeleteClass")]
		public IActionResult DeleteClass(int id)
		{
			Class c = adminManager.GetClassById(id);
			if (c != null)
			{
				adminManager.DeleteClass(c);
			}
			return RedirectToAction("Index");
		}

		private void FillStudents(ref ClassViewModel model)
		{
			var students = adminManager.GetAllStudents();

			foreach (var student in students)
			{
				model.Students.Students.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = student.LastName + " " + student.FirstName + " (" + student.Email + ")",
					Value = student.Id.ToString()
				});
			}
		}

		private void FillClassTeachers(ref ClassViewModel model)
		{
			var teachers = adminManager.GetAllClassTeachers();

			foreach (var t in teachers)
			{
				model.ClassTeacher.ClassTeachers.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = t.LastName + " " + t.FirstName + " (" + t.Email + ")",
					Value = t.Id.ToString()
				});
			}
		}

		private void FillSubjects(ref ClassViewModel model)
		{
			var subjects = adminManager.GetAllSubjects();

			foreach (var subject in subjects)
			{
				model.Subjects.Subjects.Add(new Microsoft.AspNetCore.Mvc.Rendering.SelectListItem()
				{
					Text = subject.Name,
					Value = subject.Id.ToString()
				});
			}
		}
	}
}

ElectronicClassbook/Web/Areas/Admin/Views/Class/AddClass.cshtml
@model Web.Areas.Admin.Models.ClassViewModel

@{
    ViewData["Title"] = "Přidat třídu";
    Layout = "_AdminLayout";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Přidat novou třídu</h5>
            </div>

            <div class="card-body">
                <form asp-action="AddClass">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>


                    <div class="form-group row">
                        @Html.LabelFor(model => model.ClassTeacher.ClassTeacherId, new { @class = "col-sm-2 col-form-label" })
                        <select class="form-control" asp-for="ClassTeacher.ClassTeacherId" asp-items="@(new SelectList(Model.ClassTeacher?.ClassTeachers, "Value", "Text"))">
                            <option disabled selected></option>
                        </select>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Students.StudentsId, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Students.StudentsId, new MultiSelectList(Model.Students.Students, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "StudentsDropdown" })
                        </div>
                    </div>
                    <div class="form-group row">
                        @Html.LabelFor(model => model.Subjects.SubjectsId, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Subjects.SubjectsId, new MultiSelectList(Model.Subjects.Subjects, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "SubjectsDropdown" })
                        </div>
                    </div>

                    <div>
                        <div class="form-group d-inline float-right">
                            <input type="submit" value="Vytvořit třídu" class="btn btn-primary" />
                        </div>
                        <div class="d-inline">
                            <a asp-action="Index">Zpět</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


ElectronicClassbook/Web/Areas/Admin/Views/Class/DetailClass.cshtml
@model Web.Areas.Admin.Models.ClassDetailViewModel

@{
    ViewData["Title"] = "Detail třídy";
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Detail třídy</h5>
            </div>

            <div class="card-body">
                <div class="form-group col-md">
                    <label asp-for="Name" class="control-label"></label>
                    <label class="form-control">@Model.Name</label>
                </div>


                <div class="form-group row">
                    @Html.LabelFor(model => model.ClassTeacher, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-6">
                        @if (Model.ClassTeacher != null)
                        {
                            <p>@Model.ClassTeacher?.LastName @Model.ClassTeacher?.FirstName (@Model.ClassTeacher?.Email)</p>
                        }
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Students, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-6">
                        <ul>
                            @if (Model.Students.Count > 0)
                            {
                                @foreach (var student in Model.Students)
                                {
                                    <li>@student.LastName @student.FirstName (@student.Email)</li>
                                }
                            }
                        </ul>
                    </div>
                </div>

                <div class="form-group row">
                    @Html.LabelFor(model => model.Subjects, new { @class = "col-sm-2 col-form-label" })
                    <div class="col-sm-6">
                        <ul>
                            @if (Model.Subjects.Count > 0)
                            {
                                @foreach (var subject in Model.Subjects)
                                {
                                    <li>@subject.Code - @subject.Name</li>
                                }
                            }
                        </ul>
                    </div>
                </div>

                <div>
                    <a asp-action="Index">Zpět</a>
                </div>
            </div>
        </div>
    </div>
</div>


ElectronicClassbook/Web/Areas/Admin/Views/Class/EditClass.cshtml
@model Web.Areas.Admin.Models.ClassViewModel

@{
    ViewData["Title"] = "Editovat třídu";
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Editovat třídu</h5>
            </div>

            <div class="card-body">
                <form asp-action="EditClass">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

                    @Html.HiddenFor(model => model.Id)

                    <div class="form-group">
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>


                    <div class="form-group row">
                        @Html.LabelFor(model => model.ClassTeacher.ClassTeacherId, new { @class = "col-sm-2 col-form-label" })
                        <select class="form-control" asp-for="ClassTeacher.ClassTeacherId" asp-items="@(new SelectList(Model.ClassTeacher?.ClassTeachers, "Value", "Text"))">
                            <option disabled selected></option>
                        </select>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Students.StudentsId, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Students.StudentsId, new MultiSelectList(Model.Students.Students, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "StudentsDropdown" })
                        </div>
                    </div>

                    <div class="form-group row">
                        @Html.LabelFor(model => model.Subjects.SubjectsId, new { @class = "col-sm-2 col-form-label" })
                        <div class="col-sm-6">
                            @Html.ListBoxFor(model => model.Subjects.SubjectsId, new MultiSelectList(Model.Subjects.Subjects, "Value", "Text"), new { @class = "form-control", multiple = "multiple", id = "SubjectsDropdown" })
                        </div>
                    </div>

                    <div>
                        <div class="form-group d-inline float-right">
                            <input type="submit" value="Potvrdit změnu" class="btn btn-primary" />
                        </div>
                        <div class="d-inline">
                            <a asp-action="Index">Zpět</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



ElectronicClassbook/Web/Areas/Admin/Views/Class/Index.cshtml
@model PaginatedList<Web.Areas.Admin.Models.ClassViewModel>
@{
    ViewData["Title"] = "Třídy";
    Layout = "_AdminLayout";
}


<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5 class="d-inline">Třídy</h5>

                @* Tlačítko na přidání třídy *@
                <div class="float-right d-inline">
                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Class" asp-action="AddClass">Přidat třídu</a>
                </div>
            </div>

            <div class="card-body">
                @if (Model.Count > 0)
                {
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th scope="col"> Název</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Name)
                                        </td>
                                        <td>
                                            <div class="container">
                                                <div class="btn-group blocks" role="button">
                                                    <a class="btn btn-primary" asp-area="Admin" asp-controller="Class" asp-action="DetailClass" asp-route-id="@item.Id">Detail</a>
                                                    <a class="btn btn-success" asp-area="Admin" asp-controller="Class" asp-action="EditClass" asp-route-id="@item.Id">Edit</a>
                                                    <a class="btn btn-danger" asp-area="Admin" asp-controller="Class" asp-action="DeleteClass" asp-route-id="@item.Id">Smazat</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>

                    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                    var nextDisabled = !Model.HasNextPage ? "disabled" : "";


                    <a asp-action="Index"
                       asp-route-pageNumber="@(Model.PageIndex - 1)"
                       class="btn btn-default @prevDisabled">
                        Předchozí
                    </a>
                    <a asp-action="Index"
                       asp-route-pageNumber="@(Model.PageIndex + 1)"
                       class="btn btn-default @nextDisabled">
                        Další
                    </a>
                }
                else
                {
                    <div>Žádné třídy k zobrazení.</div>
                }
            </div>
        </div>
    </div>
</div>