ElectronicClassbook/Web/Areas/Admin/Models/ParentViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Web.Areas.Admin.Models.Submodels;

namespace Web.Areas.Admin.Models
{
	public class ParentViewModel
	{
		[Display(Name = "Jméno")]
		[Required(ErrorMessage = "Povinná položka")]
		public string FirstName { get; set; }
		[Display(Name = "Příjmení")]
		[Required(ErrorMessage = "Povinná položka")]
		public string LastName { get; set; }
		[Display(Name = "E-mail")]
		[Required(ErrorMessage = "Povinná položka")]
		[EmailAddress]
		public string Email { get; set; }
		[Display(Name = "Adresa")]
		[Required(ErrorMessage = "Povinná položka")]
		public string Address { get; set; }
		[Display(Name = "Heslo")]
		public string Password { get; set; }

		[Display(Name = "Telefonní číslo")]
		[Required(ErrorMessage = "Povinná položka")]
		[RegularExpression(@"^[0-9]+$", ErrorMessage = "Zadejte pouze čísla.")]
		public string PhoneNumber { get; set; }
		public StudentSubModel Childrens { get; set; } = new StudentSubModel();
	}
}

ElectronicClassbook/Web/Areas/Attendance/Controllers/ParentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Attendance.Interfaces;
using DataAccess.EntityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Web.Areas.Attendance.Models;
using Web.Areas.Attendance.Models.Submodels;

namespace Web.Areas.Attendance.Controllers
{

	[Authorize(Roles = "Rodič")]
	[Area("Attendance")]
	[Route("parent")]
	public class ParentController : Controller
	{
		private readonly IParentManager parentManager;
		public ParentController(IParentManager parentManager)
		{
			this.parentManager = parentManager;
		}

		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		[Route("SendAbsentNote/{studentId}")]
		public IActionResult SendAbsentNote(int studentId, AbsentNoteViewModel model)
		{
			AbsentNote an = new AbsentNote();
			an.Created = DateTime.Today;
			an.Text = model.Text;
			an.State = parentManager.GetAbsentNoteStateByName("Odeslána");
			an.Parent = parentManager.GetParentByEmail(User.Identity.Name);
			an.Student = parentManager.GetStudentById(studentId);

			List<DataAccess.EntityModel.Attendance> absences = new List<DataAccess.EntityModel.Attendance>();
			foreach (var absence in model.Absences)
			{
				absences.Add(parentManager.GetAttendanceById(absence.Id));
			}
			an.Absences = absences;

			if (!parentManager.CreateAbsentNote(an))
			{
				ModelState.AddModelError("", "Někde se stala chyba. Omluvenka nebyla vytvořena.");
			}

			return RedirectToAction("ShowAbsences", new { id = studentId });
		}

		[HttpPost]
		[Route("CreateAbsentNote/{studentId}")]
		public IActionResult CreateAbsentNote(int studentId, AbsenceListViewModel model)
		{
			AbsentNoteViewModel m = new AbsentNoteViewModel();

			foreach(var absence in model.Absences)
			{
				if(absence.Selected)
				{
					m.Absences.AddRange(absence.Absences);
				}
			}

			if(m.Absences.Count == 0)
			{
				//error
				ModelState.AddModelError("", "Nebyla vybrána žádná absence k omluvení.");
			}

			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = studentId;

			return View(m);
		}

		[HttpGet]
		[Route("ShowAbsences")]
		public IActionResult ShowAbsences()
		{
			List<StudentInfoSubModel> kids = this.GetLayoutData();
			var kid = kids.FirstOrDefault();
			if (kid == null)
			{
				//error
			}

			return RedirectToAction("ShowAbsences", new { id = kid.Id });
		}

		[HttpGet]
		[Route("ShowAbsences/{id}")]
		[Route("ShowAbsences/{id}/{all}")]
		public IActionResult ShowAbsences(int id, bool all = false, int pageNumber=1)
		{
			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = id;

			AbsenceListViewModel model = new AbsenceListViewModel();

			// get list of absences
			List<DataAccess.EntityModel.Attendance> absences = parentManager.GetAbsenceByStudentId(id).ToList();

			if (!all)
			{
				absences = absences.Where(x => x.IsExcused == false).Where(x => (x.AbsentNoteId == null || x.AbsentNote.State.Name.Equals("Zamítnuta"))).ToList();
			}
			//Groups by created date
			var absencesByDate = absences.GroupBy(x => x.Record.Created);
			foreach (var absence in absencesByDate)
			{
				model.Absences.Add(new AbsenceInfoSubModel()
				{
					Date = absence.Key,
					MissedClasses = absence.Count(),
					Selected = false,
					Absences = absences.Where(x => x.Record.Created.Equals(absence.Key)).ToList()
				});
			}
			ViewBag.NewAbsences = absences.Where(x => (x.AbsentNoteId == null || x.AbsentNote.State.Name.Equals("Zamítnuta"))).Count(x => x.IsExcused == false);
			ViewBag.ShowAll = all;

			return View(model);
		}

		private List<StudentInfoSubModel> GetLayoutData()
		{
			Parent parent = parentManager.GetParentByEmail(User.Identity.Name);
			if(parent == null)
			{
				//error
				return new List<StudentInfoSubModel>();
			}
			List<Student> childrens = parentManager.GetStudentsByParentId(parent.Id).ToList();
			if (childrens == null || childrens.Count == 0)
			{
				//error
				return new List<StudentInfoSubModel>();
			}

			var kids = new List<StudentInfoSubModel>();
			foreach (var kid in childrens)
			{
				kids.Add(new Models.Submodels.StudentInfoSubModel()
				{
					FirstName = kid.FirstName,
					Id = kid.Id
				});
			}

			return kids;
		}
	}
}

ElectronicClassbook/Web/Areas/Reports/Controllers/ParentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Common;
using DataAccess.EntityModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Reports.Interfaces;
using Web.Areas.Reports.Models;
using Web.Areas.Reports.Models.Submodels;

namespace Web.Areas.Reports.Controllers
{

	[Authorize(Roles = "Rodič")]
	[Area("Reports")]
	[Route("parent")]
	public class ParentController : Controller
	{
		private readonly IParentStudentManager parentManager;
		public ParentController(IParentStudentManager parentManager)
		{
			this.parentManager = parentManager;
		}

		[Route("Index")]
		public IActionResult Index()
		{
			ParentReportViewModel model = new ParentReportViewModel();
			this.GetLayoutData();

			Parent parent = parentManager.GetParentByEmail(User.Identity.Name);
			if (parent == null)
			{
				//error
			}
			List<Student> childrens = parentManager.GetStudentsByParentId(parent.Id).ToList();
			if (childrens == null || childrens.Count == 0)
			{
				//error
			}

			foreach (var kid in childrens)
			{
				//get absence by student id
				List<DataAccess.EntityModel.Attendance> absence = parentManager.GetAbsencesByStudentId(kid.Id).Where(x => x.IsExcused == false)
																	.Where(x => (x.AbsentNoteId == null || x.AbsentNote.State.Name.Equals("Zamítnuta"))).ToList();

				// get homeworks by student id
				List<Homework> homeworks = parentManager.GetHomeworksByStudentId(kid.Id).Where(x => x.ShowParent == true).Where(x => x.Deadline > DateTime.Today).ToList();

				// get student's school-home notes by student's id
				List<SchoolHomeNote> notes = parentManager.GetSchoolHomeNotesByStudentId(kid.Id).Where(x => x.ShowParent == true).ToList();

				model.Students.Add(new StudentReportViewModel()
				{
					Id = kid.Id,
					FirstName = kid.FirstName,
					LastName = kid.LastName,
					Email = kid.Email,
					Absences = absence,
					Homeworks = homeworks,
					Notes = notes
				});
			}

			return View(model);
		}

		[HttpGet]
		[Route("ShowHomeworks")]
		public IActionResult ShowHomeworks()
		{
			List<StudentInfoSubModel> kids = this.GetLayoutData();
			var kid = kids.FirstOrDefault();
			if(kid == null)
			{
				//error
			}

			return RedirectToAction("ShowHomeworks", new { id = kid.Id });
		}

		[HttpGet]
		[Route("ShowHomeworks/{id}")]
		[Route("ShowHomeworks/{id}/{all}")]
		public IActionResult ShowHomeworks(int id, bool all = false, int pageNumber=1)
		{
			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = id;


			//get homeworks for student
			List<Homework> homeworks = parentManager.GetHomeworksByStudentId(id).Where(x => x.Deadline > DateTime.Today).ToList();
			if(homeworks == null)
			{
				//error
			}
			List<Homework> newHomeworks = homeworks.Where(x => x.ShowParent == true).ToList();


			HomeworkListViewModel model = new HomeworkListViewModel();
			if (all)
				model.Homeworks = PaginatedList<Homework>.Create(homeworks.AsQueryable(), pageNumber, 10);
			else
				model.Homeworks = PaginatedList<Homework>.Create(newHomeworks.AsQueryable(), pageNumber, 10);

			ViewBag.NewHomeworksCount = newHomeworks.Count(x => x.ShowParent == true);
			return View(model);
		}

		[HttpGet]
		[Route("DetailHomework/{id}/{homeworkId}")]
		public IActionResult DetailHomework(int id, int homeworkId)
		{
			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = id;

			HomeworkDetailViewModel model = new HomeworkDetailViewModel();
			Homework homework = parentManager.GetHomeworkById(homeworkId);
			if(homework == null)
			{
				//error
			}

			model.homework = homework;

			return View(model);
		}

		[HttpGet]
		[Route("HideHomework/{id}/{homeworkId}")]
		public IActionResult HideHomework(int id, int homeworkId)
		{
			//set Show property to false

			Homework homework = parentManager.GetHomeworkById(homeworkId);
			if(homework == null)
			{
				//error
			}

			homework.ShowParent = false;
			parentManager.UpdateHomework(homework);

			return RedirectToAction("ShowHomeworks", new { id });
		}


		[HttpGet]
		[Route("ShowSchoolHomeNotes")]
		public IActionResult ShowSchoolHomeNotes()
		{
			List<StudentInfoSubModel> kids = this.GetLayoutData();
			var kid = kids.FirstOrDefault();
			if (kid == null)
			{
				//error
			}

			return RedirectToAction("ShowSchoolHomeNotes", new { id = kid.Id });
		}

		[HttpGet]
		[Route("ShowSchoolHomeNotes/{id}")]
		[Route("ShowSchoolHomeNotes/{id}/{all}")]
		public IActionResult ShowSchoolHomeNotes(int id, bool all = false, int pageNumber=1)
		{
			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = id;

			List<SchoolHomeNote> notes = parentManager.GetSchoolHomeNotesByStudentId(id).ToList();
			if (notes == null)
			{
				//error
			}
			List<SchoolHomeNote> newNotes = notes.Where(x => x.ShowParent == true).ToList();

			SchoolHomeNoteListViewModel model = new SchoolHomeNoteListViewModel();
			if (all)
				model.Notes = PaginatedList<SchoolHomeNote>.Create(notes.AsQueryable(), pageNumber, 10);
			else
				model.Notes = PaginatedList<SchoolHomeNote>.Create(newNotes.AsQueryable(), pageNumber, 10);

			ViewBag.NewNotesCount = newNotes.Count(x => x.ShowParent == true);
			return View(model);
		}

		[HttpGet]
		[Route("HideSchoolHomeNote/{id}/{noteId}")]
		public IActionResult HideSchoolHomeNote(int id, int noteId)
		{
			SchoolHomeNote note = parentManager.GetSchoolHomeNoteById(noteId);
			if (note == null)
			{
				//error
			}

			note.ShowParent = false;
			parentManager.UpdateSchoolHomeNote(note);

			return RedirectToAction("ShowSchoolHomeNotes", new { id });
		}

		[HttpGet]
		[Route("ShowAbsentNotes")]
		public IActionResult ShowAbsentNotes()
		{
			List<StudentInfoSubModel> kids = this.GetLayoutData();
			var kid = kids.FirstOrDefault();
			if (kid == null)
			{
				//error
			}

			return RedirectToAction("ShowAbsentNotes", new { id = kid.Id });
		}

		[HttpGet]
		[Route("ShowAbsentNotes/{id}")]
		public IActionResult ShowAbsentNotes(int id, int pageNumber=1)
		{
			ViewBag.Childrens = this.GetLayoutData();
			ViewBag.StudentId = id;

			AbsentNoteListViewModel model = new AbsentNoteListViewModel();

			var notes = parentManager.GetAbsentNotesByStudentId(id).Where(x => x.Absences.Count() > 0).ToList();
			model.Notes = PaginatedList<AbsentNote>.Create(notes.AsQueryable(), pageNumber, 10);


			return View(model);
		}

		private List<StudentInfoSubModel> GetLayoutData()
		{
			Parent parent = parentManager.GetParentByEmail(User.Identity.Name);
			if (parent == null)
			{
				//error
			}
			List<Student> childrens = parentManager.GetStudentsByParentId(parent.Id).ToList();
			if (childrens == null || childrens.Count == 0)
			{
				//error
			}

			var kids = new List<StudentInfoSubModel>();
			foreach (var kid in childrens)
			{
				kids.Add(new Models.Submodels.StudentInfoSubModel()
				{
					FirstName = kid.FirstName,
					Id = kid.Id
				});
			}

			return kids;
		}
	}
}

ElectronicClassbook/Web/Areas/Attendance/Views/Parent/CreateAbsentNote.cshtml
@model Web.Areas.Attendance.Models.AbsentNoteViewModel

@{
    ViewData["Title"] = "Nová omluvenka";
    Layout = "~/Areas/Attendance/Views/Shared/Parent/_AbsenceLayout.cshtml";
}

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Nová omluvenka</h5>
            </div>

            <div class="card-body">
                <form asp-action="SendAbsentNote" asp-route-studentId="@ViewBag.StudentId" method="post">
                    @for (int i = 0; i < Model.Absences.Count; i++)
                    {
                        @Html.HiddenFor(x => Model.Absences[i])
                        @Html.HiddenFor(x => Model.Absences[i].Id)

                    }
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="row">
                        <div class="form-group col-md-12">
                            <textarea asp-for="Text" class="form-control" rows="10"></textarea>
                            <span asp-validation-for="Text" class="text-danger"></span>
                        </div>
                    </div>

                    <div>
                        <div class="form-group d-inline float-right">
                            @if (Model.Absences.Count > 0)
                            {
                                <button type="submit" class="btn btn-primary">Odeslat omluvenku</button>
                            }
                            else
                            {
                                <button disabled type="submit" class="btn btn-primary">Odeslat omluvenku</button>
                            }
                        </div>
                        <div class="d-inline">
                            <a asp-action="ShowAbsences" asp-route-id="@ViewBag.StudentId">Zpět</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


ElectronicClassbook/Web/Areas/Attendance/Views/Parent/ShowAbsences.cshtml
@model Web.Areas.Attendance.Models.AbsenceListViewModel

@{
    ViewData["Title"] = "Absence";
    Layout = "~/Areas/Attendance/Views/Shared/Parent/_AbsenceLayout.cshtml";
}

<div class="absence container">
    <ul class="nav nav-pills">
        <li class="nav-item">
            <a class="nav-link" asp-area="Attendance" asp-controller="Parent" asp-action="ShowAbsences" asp-route-all="false" asp-route-id="@ViewBag.StudentId">Neomluvené (@ViewBag.NewAbsences)</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" asp-area="Attendance" asp-controller="Parent" asp-action="ShowAbsences" asp-route-all="true" asp-route-id="@ViewBag.StudentId">Všechny</a>
        </li>
    </ul>
</div>

<div class="row">
    <div class="col-md-12 grid-margin">
        <div class="card">
            <div class="p-4 border-bottom bg-light">
                <h5>Seznam absencí</h5>
            </div>
            <div class="card-body">
                <form action="CreateAbsentNote" method="post">
                    @if (Model.Absences.Count > 0)
                    {
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>
                                            Datum
                                        </th>
                                        <th>
                                            Počet absencí
                                        </th>
                                        <th></th>
                                    </tr>
                                </thead>

                                <tbody>

                                    @for (int i = 0; i < Model.Absences.Count; i++)
                                    {
                                        @Html.HiddenFor(x => Model.Absences[i])

                                        <tr class="accordion-toggle">

                                            <td>
                                                @if (!ViewBag.ShowAll)
                                                {
                                                    @Html.CheckBoxFor(x => Model.Absences[i].Selected)
                                                }
                                            </td>

                                            <td>
                                                @Convert.ToString(string.Format("{0:dd/MM/yyyy}", Model.Absences[i].Date))
                                                @Html.HiddenFor(x => Model.Absences[i].Date)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x => Model.Absences[i].MissedClasses)
                                            </td>

                                            <td>
                                                <button type="button" class="btn" data-toggle="collapse" data-target=".@String.Format("a" + @i)">Detail</button>
                                            </td>
                                        </tr>
                                        <tr class="accordian-body collapse @String.Format("a" + @i)">
                                            <td colspan="4" class="hiddenRow">
                                                <div>
                                                    <table class="table table-sm table-borderless">
                                                        <thead>
                                                            <tr>
                                                                <th>
                                                                    Hodina
                                                                </th>
                                                                <th>
                                                                    Zameškaný předmět
                                                                </th>
                                                                <th>Pozdní přichod</th>
                                                            </tr>
                                                        </thead>
                                                        @for (int j = 0; j < Model.Absences[i].Absences.Count; j++)

                                                        {
                                                            @Html.HiddenFor(x => Model.Absences[i].Absences[j])
                                                            @Html.HiddenFor(x => Model.Absences[i].Absences[j].Id)

                                                            <tbody>
                                                                <tr>
                                                                    <td>
                                                                        @Model.Absences[i].Absences[j].Record.SerialNumber
                                                                    </td>
                                                                    <td>
                                                                        @Model.Absences[i].Absences[j].Record.Subject.Code
                                                                    </td>
                                                                    <td>
                                                                        @if (!Model.Absences[i].Absences[j].Present && Model.Absences[i].Absences[j].LateArrival)
                                                                        {
                                                                            <div>Ano, @Model.Absences[i].Absences[j].AbsenceInterval minut</div>
                                                                        }
                                                                        else
                                                                        {
                                                                            <div>Ne</div>
                                                                        }
                                                                    </td>
                                                                </tr>
                                                            </tbody>

                                                        }
                                                    </table>
                                                </div>
                                            </td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>

                        @if (!ViewBag.ShowAll)
                        {
                            <div>
                                <button type="submit" class="btn btn-primary float-right" asp-area="Attendance" asp-controller="Parent" asp-action="CreateAbsentNote" asp-route-studentId="@ViewBag.StudentId">Omluvit vybrané</button>
                            </div>
                        }
                    }
                    else
                    {
                        <div>Žádné absence k zobrazení.</div>
                    }

                </form>
            </div>
        </div>
    </div>
</div>
